name = "GmboltRegistry"
uuid = "f9a2729a-0030-46f8-aaf0-04242dc8596c"
repo = "https://github.com/gmbolt/GmboltRegistry.git"
description = "Local Julia registry for personal developmental code"

[packages]
292a1bb4-fa15-4f11-86f3-3196e66d7b42 = { name = "NetworkPopulations", path = "N/NetworkPopulations" }
9f172dfe-3e8c-48ce-b707-2c617ccde4b0 = { name = "NetworkDistances", path = "N/NetworkDistances" }
